In [32]:
import os
import pandas as pd 

path = 'Data' #modify path of file directory as appropriate
items = os.listdir(path)
list_of_paths = []

for a in items:
    list_of_paths.append(path + '/' + a)

def pd_analyse_water_levels(path):
    """This function takes in the file path of a csv
    perfoms analysis with pandas
    Columns in the csv are Date and time, water_levels, 
    flag which is a categorical variable 1 or 0
    """
    ld = pd.read_csv(path)
    df = ld.iloc[:,:3]
    old_column = ld.columns[:3]

    df = df.rename(columns = {old_column[0]:'datetime', old_column[1]:'water_level', old_column[2]: 'is_high_tide'})

    df['datetime'] = pd.to_datetime(df['datetime'])
    df['water_level'] = pd.to_numeric(df['water_level'], errors= 'ignore').astype(float)
    df['month'] = df['datetime'].dt.month
    df['year'] = df['datetime'].dt.year

    df_high_tide = df[df["is_high_tide"] == 1]['water_level']
    df_low_tide = df[df["is_high_tide"] == 0]['water_level']
    summary_statistics = {'tide_high': {'mean':round(df_high_tide.mean(),2), 
                'median':round(df_high_tide.median(),2), 
                'interquartile_range':round((df_high_tide.quantile(.75) - df_high_tide.quantile(.25)),2)},
    'tide_low': {'mean':round(df_low_tide.mean()), 
                'median':round(df_low_tide.median(),2), 
                'interquartile_range':round((df_low_tide.quantile(.75) - df_low_tide.quantile(.25)),2)}}

    # Calculate ratio of high tide days
    all_high_days = df.query('is_high_tide==1').groupby('year').count()['water_level']
    high_days = df.query(f'(water_level>{df_high_tide.quantile(.75)}) & (is_high_tide==1)').groupby('year').count()['water_level']
    high_ratio = (high_days/all_high_days).reset_index()

    # Calculate ratio of low tide days
    all_low_days = df.query('is_high_tide==0').groupby('year').count()['water_level']
    low_days = df.query(f'(water_level<{df_low_tide.quantile(.25)}) & (is_high_tide==0)').groupby('year').count()['water_level']
    low_ratio = (low_days/all_low_days).reset_index()

    solution = {'river': path.split('/')[1].split('.')[0],'summary_statistics':summary_statistics, 'high_ratio': high_ratio, 'low_ratio':low_ratio}
    new = high_ratio.join(low_ratio, lsuffix = '_low_ratio')
    new.to_excel('{}_levels.xlsx'.format(path.split('/')[1].split('.')[0]))
    print(solution)

In [33]:
for path in list_of_paths:
    pd_analyse_water_levels(path)

{'river': '10-11_London_Bridge', 'summary_statistics': {'tide_high': {'mean': 3.32, 'median': 3.35, 'interquartile_range': 0.74}, 'tide_low': {'mean': -2, 'median': -2.41, 'interquartile_range': 0.54}}, 'high_ratio':     year  water_level
0   1911     0.032787
1   1912     0.127469
2   1913     0.186846
3   1914     0.161572
4   1915     0.219219
..   ...          ...
80  1991     0.252125
81  1992     0.265912
82  1993     0.317597
83  1994     0.357447
84  1995     0.324823

[85 rows x 2 columns], 'low_ratio':     year  water_level
0   1911     0.203463
1   1912     0.192793
2   1913     0.102985
3   1914     0.141618
4   1915     0.139818
..   ...          ...
80  1991     0.312057
81  1992     0.265912
82  1993     0.252496
83  1994     0.252482
84  1995     0.246809

[85 rows x 2 columns]}
{'river': '15_Richmond', 'summary_statistics': {'tide_high': {'mean': 3.72, 'median': 3.76, 'interquartile_range': 0.77}, 'tide_low': {'mean': 0, 'median': 0.04, 'interquartile_range': 1.04}}, 'high_ratio':     year  water_level
0   1911     0.095238
1   1912     0.183284
2   1913     0.155556
3   1914     0.111429
4   1915     0.166667
..   ...          ...
80  1991     0.262040
81  1992     0.282885
82  1993     0.361190
83  1994     0.392092
84  1995     0.338505

[85 rows x 2 columns], 'low_ratio':     year  water_level
0   1911     0.001447
1   1912          NaN
2   1913          NaN
3   1914          NaN
4   1915          NaN
5   1916          NaN
6   1917          NaN
7   1918          NaN
8   1919          NaN
9   1920          NaN
10  1921     0.314063
11  1922     0.077042
12  1923     0.079023
13  1924     0.001435
14  1925     0.002903
15  1926     0.014493
16  1927          NaN
17  1928     0.052050
18  1930     0.164452
19  1931     0.001422
20  1932     0.022599
21  1933     0.404798
22  1934     0.735420
23  1935     0.234375
24  1936     0.100852
25  1937     0.144886
26  1938     0.548295
27  1939     0.153191
28  1940     0.316239
29  1941     0.160247
30  1942     0.372857
31  1943     0.596591
32  1944     0.700965
33  1945     0.627566
34  1946     0.285511
35  1947     0.473684
36  1948     0.550992
37  1949     0.490000
38  1950     0.351773
39  1951     0.119403
40  1952     0.286525
41  1953     0.485673
42  1954     0.287172
43  1955     0.384164
44  1956     0.527581
45  1957     0.329529
46  1958     0.126677
47  1959     0.441135
48  1960     0.200565
49  1961     0.372857
50  1962     0.358674
51  1963     0.323851
52  1964     0.453901
53  1965     0.595170
54  1966     0.143763}
{'river': '6_Tilbury', 'summary_statistics': {'tide_high': {'mean': 2.77, 'median': 2.8, 'interquartile_range': 0.67}, 'tide_low': {'mean': -2, 'median': -2.29, 'interquartile_range': 0.59}}, 'high_ratio':     year  water_level
0   1912     0.176692
1   1913     0.163389
2   1914     0.151090
3   1915     0.188136
4   1916     0.206442
..   ...          ...
79  1991     0.321986
80  1992     0.303116
81  1993     0.375887
82  1994     0.401709
83  1995     0.358464

[84 rows x 2 columns], 'low_ratio':     year  water_level
0   1912     0.234615
1   1913     0.231467
2   1914     0.261682
3   1915     0.228814
4   1916     0.273128
..   ...          ...
79  1991     0.240793
80  1992     0.194326
81  1993     0.194051
82  1994     0.184767
83  1995     0.201705

[84 rows x 2 columns]}
{'river': '4_Southend', 'summary_statistics': {'tide_high': {'mean': 2.37, 'median': 2.39, 'interquartile_range': 0.61}, 'tide_low': {'mean': -2, 'median': -2.04, 'interquartile_range': 0.56}}, 'high_ratio':     year  water_level
0   1911     0.190202
1   1912     0.231655
2   1913     0.201418
3   1914     0.206647
4   1915     0.225564
..   ...          ...
80  1991     0.291607
81  1992     0.285714
82  1993     0.377358
83  1994     0.381560
84  1995     0.369466

[85 rows x 2 columns], 'low_ratio':     year  water_level
0   1911     0.317529
1   1912     0.303030
2   1913     0.274788
3   1914     0.284892
4   1915     0.299699
..   ...          ...
80  1991     0.226138
81  1992     0.219547
82  1993     0.248547
83  1994     0.245390
84  1995     0.234399

[85 rows x 2 columns]}
{'river': '1_Walton_on_Naze', 'summary_statistics': {'tide_high': {'mean': 1.72, 'median': 1.73, 'interquartile_range': 0.46}, 'tide_low': {'mean': -1, 'median': -1.42, 'interquartile_range': 0.44}}, 'high_ratio':     year  water_level
0   1968     0.195994
1   1969     0.225532
2   1970     0.195745
3   1971     0.186969
4   1972     0.206215
5   1973     0.232624
6   1974     0.287943
7   1975     0.290141
8   1976     0.274648
9   1977     0.310638
10  1978     0.260035
11  1980     0.263285
12  1981     0.239291
13  1982     0.284091
14  1983     0.260993
15  1984     0.218440
16  1985     0.245042
17  1986     0.222380
18  1987     0.248227
19  1988     0.258156
20  1989     0.220963
21  1990     0.250354
22  1991     0.219971
23  1992     0.227723
24  1993     0.244318
25  1994     0.269886
26  1995     0.282670, 'low_ratio':     year  water_level
0   1968     0.253582
1   1969     0.239377
2   1970     0.262411
3   1971     0.252841
4   1972     0.287129
5   1973     0.254958
6   1974     0.262712
7   1975     0.204255
8   1976     0.259574
9   1977     0.226629
10  1978     0.265271
11  1980     0.273608
12  1981     0.244118
13  1982     0.188571
14  1983     0.196884
15  1984     0.247525
16  1985     0.225852
17  1986     0.268085
18  1987     0.229787
19  1988     0.226174
20  1989     0.212766
21  1990     0.250000
22  1991     0.341844
23  1992     0.247175
24  1993     0.272340
25  1994     0.249292
26  1995     0.276596}
{'river': '9_Cherry_Garden_Pier', 'summary_statistics': {'tide_high': {'mean': 3.22, 'median': 3.25, 'interquartile_range': 0.76}, 'tide_low': {'mean': -2, 'median': -2.39, 'interquartile_range': 0.58}}, 'high_ratio':     year  water_level
0   1911     0.186813
1   1912     0.245902
2   1913     0.193103
3   1914     0.191304
4   1915     0.161644
5   1916     0.231544
6   1917     0.191781
7   1918     0.194521
8   1919     0.255495
9   1920     0.217033
10  1921     0.132231
11  1922     0.162983
12  1923     0.146739
13  1924     0.233788
14  1925     0.228898
15  1926     0.217143
16  1927     0.201141
17  1928     0.241477
18  1929     0.169946
19  1930     0.196023
20  1931     0.208807
21  1932     0.177305
22  1933     0.178723
23  1934     0.111801, 'low_ratio':     year  water_level
0   1911     0.252055
1   1912     0.218579
2   1913     0.191781
3   1914     0.246377
4   1915     0.147945
5   1916     0.174497
6   1917     0.197260
7   1918     0.201102
8   1919     0.167582
9   1920     0.233516
10  1921     0.315068
11  1922     0.327869
12  1923     0.316940
13  1924     0.267581
14  1925     0.283688
15  1926     0.272989
16  1927     0.230441
17  1928     0.207681
18  1929     0.304965
19  1930     0.209929
20  1931     0.227596
21  1932     0.237288
22  1933     0.268466
23  1934     0.351240}
{'river': '12_All_Hallows_Pier', 'summary_statistics': {'tide_high': {'mean': 3.1, 'median': 3.07, 'interquartile_range': 0.51}, 'tide_low': {'mean': -2, 'median': -2.34, 'interquartile_range': 0.41}}, 'high_ratio':    year  water_level
0  1911     0.241379, 'low_ratio':    year  water_level
0  1911     0.241379}
{'river': '2_Margate', 'summary_statistics': {'tide_high': {'mean': 1.85, 'median': 1.86, 'interquartile_range': 0.5}, 'tide_low': {'mean': -2, 'median': -1.58, 'interquartile_range': 0.52}}, 'high_ratio':     year  water_level
0   1967     0.294521
1   1968     0.254597
2   1969     0.259574
3   1970     0.240741
4   1971     0.215603
5   1972     0.214516
6   1973     0.240942
7   1974     0.215630
8   1975     0.192090
9   1976     0.231638
10  1977     0.242553
11  1978     0.363636
12  1979     0.265487
13  1980     0.265528
14  1981     0.338235
15  1982     0.263848
16  1983     0.287197
17  1984     0.198185
18  1985     0.222880
19  1986     0.218905
20  1987     0.212518
21  1988     0.236070
22  1989     0.225212
23  1990     0.245852
24  1991     0.242424
25  1992     0.227737
26  1993     0.267425
27  1994     0.252648
28  1995     0.261789, 'low_ratio':     year  water_level
0   1967     0.165517
1   1968     0.241867
2   1969     0.240793
3   1970     0.242898
4   1971     0.253901
5   1972     0.310289
6   1973     0.260398
7   1974     0.329480
8   1975     0.295455
9   1976     0.303116
10  1977     0.296034
11  1978     0.437500
12  1979     0.314706
13  1980     0.318043
14  1981     0.182482
15  1982     0.254731
16  1983     0.236207
17  1984     0.267477
18  1985     0.243083
19  1986     0.224626
20  1987     0.206140
21  1988     0.192364
22  1989     0.187767
23  1990     0.161388
24  1991     0.219031
25  1992     0.217201
26  1993     0.209104
27  1994     0.195159
28  1995     0.224806}
{'river': '3_Shivering_Sand', 'summary_statistics': {'tide_high': {'mean': 2.07, 'median': 2.12, 'interquartile_range': 0.52}, 'tide_low': {'mean': -2, 'median': -1.88, 'interquartile_range': 0.57}}, 'high_ratio':    year  water_level
0  1974     0.249619, 'low_ratio':    year  water_level
0  1974     0.240122}
{'river': '7-8_Silvertown', 'summary_statistics': {'tide_high': {'mean': 3.16, 'median': 3.2, 'interquartile_range': 0.71}, 'tide_low': {'mean': -2, 'median': -2.38, 'interquartile_range': 0.59}}, 'high_ratio':     year  water_level
0   1915     0.143271
1   1916     0.182720
2   1917     0.137784
3   1918     0.133523
4   1919     0.167614
..   ...          ...
56  1986     0.298867
57  1987     0.312945
58  1988     0.310078
59  1989     0.253311
60  1990     0.353982

[61 rows x 2 columns], 'low_ratio':     year  water_level
0   1915     0.086957
1   1916     0.201991
2   1917     0.300283
3   1918     0.259574
4   1919     0.181560
..   ...          ...
56  1986     0.274148
57  1987     0.244350
58  1988     0.244582
59  1989     0.212625
60  1990     0.303167

[61 rows x 2 columns]}
{'river': '14_Strand_on_Green', 'summary_statistics': {'tide_high': {'mean': 3.48, 'median': 3.55, 'interquartile_range': 0.71}, 'tide_low': {'mean': 0, 'median': -0.64, 'interquartile_range': 0.71}}, 'high_ratio':     year  water_level
0   1911     0.176380
1   1912     0.280864
2   1913     0.219092
3   1914     0.165625
4   1915     0.250000
5   1916     0.303817
6   1917     0.212308
7   1918     0.203857
8   1919     0.184652
9   1920     0.231767
10  1921     0.121538
11  1922     0.203620
12  1923     0.280061
13  1924     0.340058, 'low_ratio':     year  water_level
0   1911     0.288372
1   1912     0.004666
2   1913     0.029921
3   1914     0.172144
4   1915     0.093168
5   1916     0.066154
6   1917     0.083981
7   1918     0.114130
8   1919     0.180995
9   1920     0.422460
10  1921     0.881801
11  1922     0.603976
12  1923     0.510703
13  1924     0.090426}
{'river': '5_Coryton', 'summary_statistics': {'tide_high': {'mean': 2.58, 'median': 2.62, 'interquartile_range': 0.65}, 'tide_low': {'mean': -2, 'median': -2.13, 'interquartile_range': 0.55}}, 'high_ratio':     year  water_level
0   1969     0.174312
1   1970     0.174468
2   1971     0.198006
3   1972     0.233429
4   1973     0.224888
5   1974     0.266003
6   1975     0.257468
7   1976     0.246088
8   1977     0.267831
9   1978     0.266382
10  1979     0.304843
11  1980     0.288344
12  1981     0.260807
13  1982     0.253275
14  1983     0.222222, 'low_ratio':     year  water_level
0   1969     0.190909
1   1970     0.258156
2   1971     0.214489
3   1972     0.225434
4   1973     0.221719
5   1974     0.280851
6   1975     0.231206
7   1976     0.273371
8   1977     0.257880
9   1978     0.272080
10  1979     0.290831
11  1980     0.267692
12  1981     0.236729
13  1982     0.214599
14  1983     0.204545}
{'river': '13_Temple_Pier', 'summary_statistics': {'tide_high': {'mean': 3.3, 'median': 3.32, 'interquartile_range': 0.69}, 'tide_low': {'mean': -2, 'median': -2.01, 'interquartile_range': 0.46}}, 'high_ratio':    year  water_level
0  1911     0.232877
1  1912     0.282192
2  1913     0.197015
3  1914     0.217877
4  1915     0.277174
5  1916     0.308743
6  1917     0.221918
7  1918     0.225000, 'low_ratio':    year  water_level
0  1911     0.273973
1  1912     0.172131
2  1913     0.143284
3  1914     0.216066
4  1915     0.136986
5  1916     0.153005
6  1917     0.260274
7  1918     0.341667}

MAKE INTO TIMESERIES FORECASTING